<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;

class KsaCitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            ['ar' => 'الرياض', 'en' => 'Riyadh'],
            ['ar' => 'جدة', 'en' => 'Jeddah'],
            ['ar' => 'مكة المكرمة', 'en' => 'Makkah'],
            ['ar' => 'المدينة المنورة', 'en' => 'Madinah'],
            ['ar' => 'الدمام', 'en' => 'Dammam'],
            ['ar' => 'الخبر', 'en' => 'Khobar'],
            ['ar' => 'الظهران', 'en' => 'Dhahran'],
            ['ar' => 'الطائف', 'en' => 'Taif'],
            ['ar' => 'بريدة', 'en' => 'Buraidah'],
            ['ar' => 'تبوك', 'en' => 'Tabuk'],
            ['ar' => 'خميس مشيط', 'en' => 'Khamis Mushait'],
            ['ar' => 'الهفوف', 'en' => 'Hofuf'],
            ['ar' => 'المبرز', 'en' => 'Mubarraz'],
            ['ar' => 'حائل', 'en' => 'Hail'],
            ['ar' => 'نجران', 'en' => 'Najran'],
            ['ar' => 'الجبيل', 'en' => 'Jubail'],
            ['ar' => 'ينبع', 'en' => 'Yanbu'],
            ['ar' => 'أبها', 'en' => 'Abha'],
            ['ar' => 'عرعر', 'en' => 'Arar'],
            ['ar' => 'سكاكا', 'en' => 'Sakakah'],
            ['ar' => 'جيزان', 'en' => 'Jazan'],
            ['ar' => 'القطيف', 'en' => 'Qatif'],
            ['ar' => 'الباحة', 'en' => 'Al Bahah'],
            ['ar' => 'القنفذة', 'en' => 'Al Qunfudhah'],
            ['ar' => 'الليث', 'en' => 'Al Lith'],
            ['ar' => 'رابغ', 'en' => 'Rabigh'],
            ['ar' => 'الخرج', 'en' => 'Al Kharj'],
            ['ar' => 'الزلفي', 'en' => 'Az Zulfi'],
            ['ar' => 'وادي الدواسر', 'en' => 'Wadi ad-Dawasir'],
            ['ar' => 'عنيزة', 'en' => 'Unaizah'],
            ['ar' => 'الرس', 'en' => 'Ar Rass'],
            ['ar' => 'تيماء', 'en' => 'Tayma'],
            ['ar' => 'الوجه', 'en' => 'Al Wajh'],
            ['ar' => 'املج', 'en' => 'Umluj'],
            ['ar' => 'ضبا', 'en' => 'Duba'],
            ['ar' => 'حقل', 'en' => 'Haql'],
            ['ar' => 'القريات', 'en' => 'Al Qurayyat'],
            ['ar' => 'طريف', 'en' => 'Turaif'],
            ['ar' => 'رفحاء', 'en' => 'Rafha'],
            ['ar' => 'العلا', 'en' => 'AlUla'],
            ['ar' => 'خيبر', 'en' => 'Khaybar'],
            ['ar' => 'المهد', 'en' => 'Al Mahd'],
            ['ar' => 'بدر', 'en' => 'Badr'],
            ['ar' => 'الحناكية', 'en' => 'Al Henakiyah'],
            ['ar' => 'الغاط', 'en' => 'Al Ghat'],
            ['ar' => 'شقراء', 'en' => 'Shaqra'],
            ['ar' => 'الدوادمي', 'en' => 'Ad Dawadimi'],
            ['ar' => 'عفيف', 'en' => 'Afif'],
            ['ar' => 'القويعية', 'en' => 'Al Quwayiyah'],
            ['ar' => 'المزاحمية', 'en' => 'Al Muzahimiyah'],
            ['ar' => 'رماح', 'en' => 'Rumah'],
            ['ar' => 'ثادق', 'en' => 'Thadiq'],
            ['ar' => 'حريملاء', 'en' => 'Huraymila'],
            ['ar' => 'الدرعية', 'en' => 'Diriyah'],
            ['ar' => 'المجمعة', 'en' => 'Al Majmaah'],
            ['ar' => 'الأرطاوية', 'en' => 'Artawiyah'],
            ['ar' => 'رياض الخبراء', 'en' => 'Riyadh Al Khabra'],
            ['ar' => 'البكيرية', 'en' => 'Al Bukayriyah'],
            ['ar' => 'الشماسية', 'en' => 'Ash Shimasiyah'],
            ['ar' => 'النبهانية', 'en' => 'An Nabhaniyah'],
            ['ar' => 'الأسياح', 'en' => 'Al Asyah'],
            ['ar' => 'البدائع', 'en' => 'Al Badai'],
            ['ar' => 'الحائط', 'en' => 'Al Hait'],
            ['ar' => 'الشنان', 'en' => 'Ash Shinan'],
            ['ar' => 'موقق', 'en' => 'Mawqaq'],
            ['ar' => 'الغزالة', 'en' => 'Al Ghazalah'],
            ['ar' => 'بقعاء', 'en' => 'Baqaa'],
            ['ar' => 'الشويحطية', 'en' => 'Ash Shuwayhitiyah'],
            ['ar' => 'فيد', 'en' => 'Fayd'],
            ['ar' => 'الحجرة', 'en' => 'Al Hajrah'],
            ['ar' => 'أم الجماجم', 'en' => 'Umm al Jamajim'],
            ['ar' => 'الحفيرة', 'en' => 'Al Hafr'],
            ['ar' => 'قبة', 'en' => 'Qubah'],
            ['ar' => 'الحفر', 'en' => 'Al Hafar'],
            ['ar' => 'النعيرية', 'en' => 'Nairyah'],
            ['ar' => 'رأس تنورة', 'en' => 'Ras Tanura'],
            ['ar' => 'بقيق', 'en' => 'Buqayq'],
            ['ar' => 'الأحساء', 'en' => 'Al Ahsa'],
            ['ar' => 'العيون', 'en' => 'Al Oyoun'],
            ['ar' => 'الجفر', 'en' => 'Al Jafr'],
            ['ar' => 'حرض', 'en' => 'Haradh'],
            ['ar' => 'العديد', 'en' => 'Al Udeid'],
            ['ar' => 'الخفجي', 'en' => 'Khafji'],
            ['ar' => 'صفوى', 'en' => 'Safwa'],
            ['ar' => 'سيهات', 'en' => 'Sayhat'],
            ['ar' => 'تاروت', 'en' => 'Tarout'],
            ['ar' => 'الجش', 'en' => 'Al Jish'],
            ['ar' => 'العوامية', 'en' => 'Awamiyah'],
            ['ar' => 'القديح', 'en' => 'Qudaih'],
            ['ar' => 'أنك', 'en' => 'Anak'],
            ['ar' => 'بيشة', 'en' => 'Bisha'],
            ['ar' => 'خميس مشيط', 'en' => 'Khamis Mushayt'],
            ['ar' => 'أحد رفيدة', 'en' => 'Ahad Rafidah'],
            ['ar' => 'سراة عبيدة', 'en' => 'Sarat Abidah'],
            ['ar' => 'تنومة', 'en' => 'Tanomah'],
            ['ar' => 'النماص', 'en' => 'Al Namas'],
            ['ar' => 'بلقرن', 'en' => 'Balqarn'],
            ['ar' => 'بارق', 'en' => 'Bariq'],
            ['ar' => 'رجال ألمع', 'en' => 'Rijal Almaa'],
            ['ar' => 'محايل', 'en' => 'Muhayil'],
            ['ar' => 'البرك', 'en' => 'Al Birk'],
            ['ar' => 'العرضيات', 'en' => 'Al Ardiyat'],
            ['ar' => 'ثربان', 'en' => 'Thurban'],
            ['ar' => 'العيدابي', 'en' => 'Al Eidabi'],
            ['ar' => 'المندق', 'en' => 'Al Mandaq'],
            ['ar' => 'القرى', 'en' => 'Al Qura'],
            ['ar' => 'غامد الزناد', 'en' => 'Ghamid al Zinad'],
            ['ar' => 'العقيق', 'en' => 'Al Aqiq'],
            ['ar' => 'بني حسن', 'en' => 'Bani Hassan'],
            ['ar' => 'القلعة', 'en' => 'Al Qalah'],
            ['ar' => 'صامطة', 'en' => 'Samtah'],
            ['ar' => 'أبو عريش', 'en' => 'Abu Arish'],
            ['ar' => 'صبيا', 'en' => 'Sabya'],
            ['ar' => 'بيش', 'en' => 'Baysh'],
            ['ar' => 'فرسان', 'en' => 'Farasan'],
            ['ar' => 'الدرب', 'en' => 'Ad Darb'],
            ['ar' => 'الحرث', 'en' => 'Al Harth'],
            ['ar' => 'ضمد', 'en' => 'Damad'],
            ['ar' => 'الريث', 'en' => 'Ar Rayth'],
            ['ar' => 'أحد المسارحة', 'en' => 'Ahad al Masarihah'],
            ['ar' => 'الطوال', 'en' => 'At Tuwal'],
            ['ar' => 'العارضة', 'en' => 'Al Aridah'],
            ['ar' => 'ظهران الجنوب', 'en' => 'Dhahran al Janub'],
            ['ar' => 'حبونا', 'en' => 'Habuna'],
            ['ar' => 'بدر الجنوب', 'en' => 'Badr al Janub'],
            ['ar' => 'ثار', 'en' => 'Thar'],
            ['ar' => 'يدمة', 'en' => 'Yadamah'],
            ['ar' => 'الخرخير', 'en' => 'Al Kharkhir'],
            ['ar' => 'شرورة', 'en' => 'Sharurah'],
        ];

        foreach ($cities as $cityData) {
            City::create([
                'name' => json_encode($cityData),
                'is_active' => true,
            ]);
        }

        $this->command->info('KSA Cities seeded successfully!');
    }
}
