<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/

Route::group(['prefix' => 'user', 'namespace' => 'User'], function () {
    // Home Page

    Route::group(['namespace' => 'Auth'], function () {
        // Register
        Route::post('register', 'RegisterController');
        // Login
        Route::post('forgot-password', 'ForgetPasswordController');
        Route::post('reset-password', 'ResetPasswordController');

        Route::post('login', 'LoginController');
        Route::post('verify-account', 'VerifyAccountController');
        Route::group(['namespace' => 'Social'], function () {
        Route::post('social-login', 'LoginController');
        Route::post('social-register', 'RegisterController');


        });
    });

    Route::get('partners', 'PartnerController@index');
    Route::get('sellers', 'SellerUserController@index');

    Route::get('notifications', 'NotificationController@index');
    Route::get('notifications/unread-count', 'NotificationController@unreadCount');
    Route::post('notifications/mark-all-read', 'NotificationController@markAllAsRead');
    Route::post('notifications/{id}/mark-read', 'NotificationController@markAsRead');




//    Route::group(['middleware' => ['auth:api']], function() {
    Route::group(['namespace' => 'Profile'], function(){
        Route::get('video', 'UserProfileController@OtherVideo');
        Route::get('only-me-video', 'UserProfileController@myVideo');
        Route::get('profile', 'UserProfileController');
        Route::get('balance', 'UserProfileController@balance');
        Route::get('wallet', 'UserProfileController@wallet');
        Route::get('organizer-stats', 'UserProfileController@organizerStats');
        Route::post('profile_completed', 'ProfileCompleteController');

        Route::get('my-cart', 'UserProfileController@MyCart');
        Route::post('cart/add-address', 'UserProfileController@addAddress');

        Route::get('item-services', 'PieceServiceController@types');
        Route::post('piece-services', 'PieceServiceController@store');
        Route::post('piece-services/{id}', 'PieceServiceController@update');
        Route::delete('piece-services/{id}', 'PieceServiceController@destroy');

        Route::get('user-profile/{user_name}', 'UserProfileController@otherUserprofile');
        Route::post('logout', 'UserProfileController@logout');
        Route::post('delete-account', 'UserProfileController@deleteAccount');
        Route::post('update-name', 'UpdateProfileController@updateName');
        Route::post('update-profile', 'UpdateProfileController@updateProfile');

        Route::post('update-username', 'UpdateProfileController@updateUserName');
        Route::post('update-bio', 'UpdateProfileController@updateBio');
        Route::post('update-image', 'UpdateProfileController@updateImage');
        Route::post('update-files', 'UpdateProfileController@updateFiles');
        Route::post('update-password', 'ChangePasswordController');
        Route::post('profile-view/{id}', 'ProfileActionController@profileView');
        Route::get('profile-view-list', 'ProfileActionController@profileViewList');
        Route::post('block/{id}', 'ProfileActionController@block');
        Route::post('is-block/{id}', 'ProfileActionController@isBlock');
        Route::get('block-list', 'ProfileActionController@blockList');
        Route::post('update-fcm', 'UserProfileController@updateFcm');
        Route::post('update-lang', 'UserProfileController@updateLang');
        Route::post('subscription', 'UserCoinController@subscription');
        Route::get('subscription-list', 'UserCoinController@subscriptionList');

        // User Package Subscriptions - Public endpoint for plans
        Route::get('subscription-plans', 'AuctionSubscriptionController@getPlans');



    });

    // Seller invoice PDF: a directly-clickable download link (no
    // Authorization header, and no x-api-key either — a plain browser
    // tab/click can't attach any custom header at all), so it sits outside
    // auth:api and skips the blanket APISettings x-api-key check (applied to
    // every other /api/* route in routes/api.php), relying instead entirely
    // on Laravel's own request signing. The signed id+seller_id pair is only
    // ever generated by UserAuctionController::formatSellerInvoiceOrder() for
    // that seller's own invoice, and tampering with either value invalidates
    // the signature — that's the real security boundary here, not the
    // shared API key (which would otherwise have to be embedded in every
    // shareable link, defeating its purpose as a secret).
    Route::get('auction/seller-invoice/{id}/pdf', '\App\Http\Controllers\api\User\Invoice\UserAuctionController@downloadSellerInvoicePdf')
        ->middleware('signed')
        ->withoutMiddleware('APISettings')
        ->name('api.seller-invoice.pdf');

        Route::post('seller-submissions', 'SellerSubmissionController@store');

//    });

});

    Route::group(['prefix' => 'video','namespace' => 'Video'], function(){

        Route::group(['prefix' => 'auctions'], function() {
            Route::get('list/{id}', 'AuctionVideoController@list');
            Route::get('replay-list/{id}', 'AuctionVideoController@listReplay');
        });

    });


            Route::group(['prefix' => 'user','namespace' => 'User'], function(){

                Route::group(['prefix' => 'follow'], function(){
                    Route::get('followers-list/{id}', 'FollowUserController@followersList');
                });
                Route::group(['prefix' => 'friend','namespace' => 'Friend'], function(){
                    Route::get('search', 'FriendController@search');
                    Route::post('suggest', 'FriendController@suggest');
                    Route::get('video', 'FriendController@video');
                    Route::get('video/view-count', 'FriendController@viewCount');

                });
                Route::post('report-add/{id}', 'UserReportController@add');



            });





Route::group(['middleware' => ['auth:api']], function() {

        Route::group(['prefix' => 'user','namespace' => 'User'], function(){

            Route::group(['namespace' => 'Profile'], function(){
                // User Package Subscriptions - Protected routes
                Route::get('subscription-status', 'AuctionSubscriptionController@getStatus');
                Route::get('subscription-history', 'AuctionSubscriptionController@getHistory');
                Route::post('subscription', 'AuctionSubscriptionController@subscribe');
                Route::post('subscription/renew', 'AuctionSubscriptionController@renew');
            });

            Route::get('seller-submissions/my-list', 'SellerSubmissionController@myList');
            Route::get('seller-submissions/{id}', 'SellerSubmissionController@show');

            Route::group(['prefix' => 'follow'], function(){
                Route::get('list', 'FollowUserController@list');
                Route::get('followers-list', 'FavoritesVideoController@followersList');

                Route::post('add/{id}', 'FollowUserController@add');
                Route::post('unfollow/{id}', 'FollowUserController@unfollow');
            });

            Route::group(['prefix' => 'auction','namespace' => 'Invoice'], function(){
                Route::get('invoice', 'AuctionController@list');
                Route::get('invoice/{id}', 'AuctionController@Iteam');

                Route::get('user-invoice', 'UserAuctionController@list');
                Route::get('user-invoice/{id}', 'UserAuctionController@Iteam');
                Route::get('user-invoice/{id}/pdf', 'UserAuctionController@downloadInvoicePdf');
                Route::post('upload-win-video/{id}', 'UserAuctionController@uploadWinVideo');
                Route::post('upload-payment-proof', 'UserAuctionController@uploadPaymentProof');

                Route::get('seller-invoice-list', 'UserAuctionController@sellerInvoiceList');
                // seller-invoice/{id}/pdf lives outside this auth:api group — see the
                // public routes block above (signed URL instead of a bearer token).
                Route::get('partner-invoice-items', 'UserAuctionController@partnerInvoiceItemList');

            });

            Route::group(['prefix' => 'friend','namespace' => 'Friend'], function(){
                Route::post('add/{id}', 'FriendController@add');
                Route::post('unfriend/{id}', 'FriendController@unfriend');
                Route::get('list', 'FriendController@List');
                Route::get('request-list', 'FriendController@requestList');
                Route::get('my-send-request-list', 'FriendController@myRequestList');
                Route::post('accept-friend-request/{id}', 'FriendController@acceptFriendRequest');

            });


        });


        Route::group(['prefix' => 'home','namespace' => 'Home'], function () {
            Route::get('video-follow/list', 'HomeVideoController@followVideo');
        });


        Route::group(['prefix' => 'video','namespace' => 'Video'], function(){
            Route::post('add', 'VideoController');
            Route::post('add-view/{id}', 'VideoController@addView');
            Route::post('delete/{id}', 'VideoController@delete');
            Route::post('add-share/{id}', 'VideoController@addShare');


            Route::get('video-search-name/{name}', 'VideoController@searchName');
            Route::get('search-user-name-video/{name}', 'VideoController@searchUserName');


            Route::group(['prefix' => 'like'], function(){
                Route::post('{id}', 'LikeVideoController');
                Route::post('add/{id}', 'LikeVideoController@add');
                Route::post('dislike/{id}', 'LikeVideoController@dislike');
            });
            Route::group(['prefix' => 'auctions'], function(){
                Route::post('add', 'AuctionVideoController@add');
                Route::post('add-replay', 'AuctionVideoController@addReplay');
                Route::group(['prefix' => 'like'], function(){
                    Route::post('add/{id}', 'AuctionVideoController@addLike');
                    Route::post('dislike/{id}', 'AuctionVideoController@dislike');
                });


            });
            Route::group(['prefix' => 'comment'], function(){
                Route::post('add', 'CommentVideoController@add');
                Route::get('list/{id}', 'CommentVideoController@list');

            });



            Route::group(['prefix' => 'favorites'], function(){
                Route::get('list', 'FavoritesVideoController');
                Route::post('add/{id}', 'FavoritesVideoController@add');
                Route::post('unfavorited/{id}', 'FavoritesVideoController@unfavorited');
            });
            Route::group(['prefix' => 'report'], function(){
                Route::post('add/{id}', 'VideoReportController@add');
            });
        });


        Route::group(['prefix' => 'live','namespace' => 'Live'], function(){
            Route::post('add', 'LiveVideoController@add');
            Route::post('start/{id}', 'LiveVideoController@start');
            Route::get('last-auction/{id}', 'LiveVideoController@lastAuction');
            Route::post('end/{id}', 'LiveVideoController@end');
            Route::post('update/{id}', 'LiveVideoController@update');
            Route::post('delete/{id}', 'LiveVideoController@delete');
            Route::post('update-time/{id}', 'LiveVideoController@updateTime');
            Route::post('add-like/{id}', 'LiveVideoController@addLike');
            Route::get('like-count/{id}', 'LiveVideoController@LikeCount');
            Route::get('list-user', 'LiveVideoController@ListUser');
            Route::get('my-list', 'LiveVideoController@myList');
            Route::get('my-video-view/{id}', 'LiveVideoController@myVideoViewList');

            Route::get('video/{id}', 'LiveVideoController@SingleVideo');
            Route::post('send-gift', 'LiveVideoController@sendGift');
            Route::post('add-view/{id}', 'LiveVideoController@addView');
            Route::post('leave-view/{id}', 'LiveVideoController@leaveView');
            Route::get('refresh-token/{id}', 'LiveVideoController@refreshAgoraToken');
            Route::group(['prefix' => 'items'], function(){
                Route::post('add/{id}', 'LiveVideoItemController@add');
                Route::post('update/{id}', 'LiveVideoItemController@update');
                Route::post('delete/{id}', 'LiveVideoItemController@delete');
                Route::post('start/{id}', 'LiveVideoItemController@start');
                Route::post('end/{id}', 'LiveVideoItemController@end');
                Route::get('last-auction/{id}', 'LiveVideoItemController@lastAuction');
                Route::post('auction-award/{id}', 'LiveVideoItemController@auctionAward');

                // Manage a single piece inside an item's "pieces" array,
                // independent of the item's other fields. {id} is the
                // live_video_item_id for add, and the piece's own id for
                // update/delete — same {id}-in-URL convention as the item
                // routes above. Only the organizer who owns the item's
                // auction may call these (see
                // LiveVideoItemController::userOwnsItemsAuction()).
                Route::group(['prefix' => 'pieces'], function(){
                    Route::post('add/{id}', 'LiveVideoItemController@addPiece');
                    Route::post('update/{id}', 'LiveVideoItemController@updatePiece');
                    Route::post('delete/{id}', 'LiveVideoItemController@deletePiece');
                });
            });
        });
        Route::group(['prefix' => 'story','namespace' => 'Story'], function(){
            Route::post('add', 'StoryController');
            Route::get('my-list', 'StoryController@myList');
            Route::get('my-active', 'StoryController@myActive');
            Route::post('add-view/{id}', 'StoryController@addView');
            Route::get('list', 'StoryController@showList');

        });

     });

        Route::group(['prefix' => 'home','namespace' => 'Home'], function () {
            Route::get('video/list', 'HomeVideoController');
            Route::get('video/{id}', 'HomeVideoController@show');
            Route::get('user-videos/{id}', 'HomeVideoController@userVideos');
            Route::get('auctions/search', 'AuctionSearchController@search');
            Route::get('auctions/filter', 'AuctionSearchController@filter');

        });
        Route::group(['prefix' => 'video','namespace' => 'Video'], function(){
            Route::post('add-view/{id}', 'VideoController@addView');
            Route::post('add-share/{id}', 'VideoController@addShare');

        });


